### ISSUE TITLE
introduce ourselfs

### ISSUE THREAD

**Issue by bitboxer** [Malwine/juniors-in-berlin#3]
We should introduce ourselfs. Here is a start:

Bodo is a developer at bitcrowd and is currently preparing their Junior Developer Curriculum.
Malwine works as a junior at Dawanda.

Both want to encourage people to hire juniors. You can’t hire Seniors without someone giving Juniors a chance. And that someone should be you ;)

**Comment by Malwine** [comment]
I think that is good :)  Will add.
According to Sven we could also try to make the purpose of the list clearer.

**Comment by bitboxer** [comment]
Yes, but I think that should be another ticket. The introduction is done. Closing :wink:
